---
abstract: 'type constraints for Bytes and Chars'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
  Test::TypeTiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Types-Encodings
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Types::Encodings:
    file: lib/Types/Encodings.pm
    version: 0.002
requires:
  Type::Library: 0.004
  perl: 5.008001
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Types-Encodings/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Types-Encodings
  homepage: https://metacpan.org/release/Types-Encodings
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-types-encodings.git
version: 0.002
